### PR TITLE
PAM configuration fixes

### PR DESCRIPTION
**Pull request by marineam**
/cc @mjg59 

Fixes https://github.com/coreos/bugs/issues/1460

### CODE REVIEW

**Comment by mjg59** [comment]
lgtm

**Comment by crawford** [comment]
@marineam have you had a chance to test these changes out? Is there anything I can do to help?

**Comment by marineam** [comment]
I've confirmed that these changes work. We certainly need to set up some automated sssd testing considering password login with LDAP accounts was broken prior to this. Perhaps we could use sssd's special 'LOCAL' domain which uses a on-disk db instead of a remote service.

Changing passwords of LDAP accounts remains problematic: If the account is duplicated locally it should work but if it is only in LDAP the pam_unix module will not prompt for a new password and the use_authtok option on pam_sss prevents it from prompting itself. If the option is removed then the LDAP only case works but I suspect the duplicated locally case will cause both pam_unix and pam_sss to prompt for the new password, which would be confusing. All this just works in the more typical setup that uses pam_cracklib.

**Comment by marineam** [comment]
Also, it seems sssd will not create home directories for ldap accounts. Should we add that to the default pam config?

**Pull request merged**
